-- List of all common GTA V animal models
PedModels = {}

PedModels.Animals = {
    [GetHashKey("a_c_boar")] = "Boar",
    [GetHashKey("a_c_cat_01")] = "Cat",
    [GetHashKey("a_c_chickenhawk")] = "Chickenhawk",
    [GetHashKey("a_c_chimp")] = "Chimp",
    [GetHashKey("a_c_chop")] = "Chop",
    [GetHashKey("a_c_cormorant")] = "Cormorant",
    [GetHashKey("a_c_cow")] = "Cow",
    [GetHashKey("a_c_coyote")] = "Coyote",
    [GetHashKey("a_c_crow")] = "Crow",
    [GetHashKey("a_c_deer")] = "Deer",
    [GetHashKey("a_c_dolphin")] = "Dolphin",
    [GetHashKey("a_c_fish")] = "Fish",
    [GetHashKey("a_c_hen")] = "Hen",
    [GetHashKey("a_c_humpback")] = "Humpback Whale",
    [GetHashKey("a_c_husky")] = "Husky",
    [GetHashKey("a_c_mtlion")] = "Mountain Lion",
    [GetHashKey("a_c_pig")] = "Pig",
    [GetHashKey("a_c_pigeon")] = "Pigeon",
    [GetHashKey("a_c_poodle")] = "Poodle",
    [GetHashKey("a_c_pug")] = "Pug",
    [GetHashKey("a_c_rabbit_01")] = "Rabbit",
    [GetHashKey("a_c_rat")] = "Rat",
    [GetHashKey("a_c_retriever")] = "Retriever",
    [GetHashKey("a_c_rhesus")] = "Rhesus Monkey",
    [GetHashKey("a_c_rottweiler")] = "Rottweiler",
    [GetHashKey("a_c_seagull")] = "Seagull",
    [GetHashKey("a_c_sharkhammer")] = "Hammerhead Shark",
    [GetHashKey("a_c_sharktiger")] = "Tiger Shark",
    [GetHashKey("a_c_shepherd")] = "Shepherd",
    [GetHashKey("a_c_stingray")] = "Stingray",
    [GetHashKey("a_c_westy")] = "Westy",
}
